### ISSUE TITLE
rdk deploy (without -f) do not support Managed Rules parameters.json

### ISSUE THREAD

**Issue by jongogogo** [awslabs/aws-config-rdk#124]
Parameters.json:
```
{
  "Version": "1.0",
  "Parameters": {
    "RuleName": "GUARDDUTY_ENABLED_CENTRALIZED",
    "SourceRuntime": null,
    "CodeKey": null,
    "InputParameters": "{}",
    "OptionalParameters": "{\"CentralMonitoringAccount\":\"\"}",
    "SourcePeriodic": "TwentyFour_Hours",
    "SourceIdentifier": "GUARDDUTY_ENABLED_CENTRALIZED",
    "RuleSets": [
      "baseline",
      "rulecriticity:high",
      "pci",
      "pci:10.6",
      "guardduty"
    ]
  }
}
```

Error:
```
> rdk deploy GUARDDUTY_ENABLED_CENTRALIZED
Running deploy!
Zipping GUARDDUTY_ENABLED_CENTRALIZED
Uploading GUARDDUTY_ENABLED_CENTRALIZED
Upload complete.
Creating CloudFormation Stack for GUARDDUTY_ENABLED_CENTRALIZED
Traceback (most recent call last):
  File "C:\Users\jrault\AppData\Local\Programs\Python\Python36\lib\site-packages\rdk\rdk.py", line 692, in deploy
    my_stack = my_cfn.describe_stacks(StackName=my_stack_name)
  File "C:\Users\jrault\AppData\Local\Programs\Python\Python36\lib\site-packages\botocore\client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "C:\Users\jrault\AppData\Local\Programs\Python\Python36\lib\site-packages\botocore\client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ValidationError) when calling the DescribeStacks operation: Stack with id GUARDDUTYENABLEDCENTRALIZED does not exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jrault\AppData\Local\Programs\Python\Python36\Scripts\rdk", line 33, in <module>
    return_val = my_rdk.process_command()
  File "C:\Users\jrault\AppData\Local\Programs\Python\Python36\lib\site-packages\rdk\rdk.py", line 68, in process_command
    exit_code = method_to_call()
  File "C:\Users\jrault\AppData\Local\Programs\Python\Python36\lib\site-packages\rdk\rdk.py", line 736, in deploy
    'CAPABILITY_IAM',
  File "C:\Users\jrault\AppData\Local\Programs\Python\Python36\lib\site-packages\botocore\client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "C:\Users\jrault\AppData\Local\Programs\Python\Python36\lib\site-packages\botocore\client.py", line 586, in _make_api_call
    api_params, operation_model, context=request_context)
  File "C:\Users\jrault\AppData\Local\Programs\Python\Python36\lib\site-packages\botocore\client.py", line 621, in _convert_to_request_dict
    api_params, operation_model)
  File "C:\Users\jrault\AppData\Local\Programs\Python\Python36\lib\site-packages\botocore\validate.py", line 291, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid type for parameter Parameters[3].ParameterValue, value: None, type: <class 'NoneType'>, valid types: <class 'str'>
Invalid type for parameter Parameters[7].ParameterValue, value: None, type: <class 'NoneType'>, valid types: <class 'str'>
```

**Comment by jongogogo** [comment]
Any update @michaelborchert ?

**Comment by Kaikj** [comment]
I am encountering this issue too.

Seems like `null` or an empty string is not supported for `SourceRuntime` parameter as can be seen from [here](https://github.com/awslabs/aws-config-rdk/blob/master/rdk/rdk.py#L1777). Would appreciate to get some guidance on what should be done in the case of managed rules. I can open a PR to get a fix in for this if it helps.

**Comment by michaelborchert** [comment]
If you have a PR I'd be happy to take a look and merge it in.

**Comment by Kaikj** [comment]
@michaelborchert Sorry but I don't have one yet as I am unsure about the expected behavior. Perhaps you could give me some guidance on what the expectation is?

**Comment by jongogogo** [comment]
@Kaikj FYI, PR with the fix
