### ISSUE TITLE
Common Testing fails if "evaluate_parameters" function raises any any exception

### ISSUE THREAD

**Issue by rafihm** [awslabs/aws-config-rdk#150]
The test template has two Common testing functions "`test_sts_unknown_error(self)`" and "`test_sts_access_denied(self)`",
When we are doing local test (`rdk test-local <rule>` ) above two tests fails if "`evaluate_parameters`" has any condition for raising exception. 

Test Output.
```
======================================================================
FAIL: test_sts_access_denied (EEFS_NOT_ENCRYPTED_test.TestStsErrors)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/rafih/pro-service/virt-rdk/EEFS_NOT_ENCRYPTED/EEFS_NOT_ENCRYPTED_test.py", line 163, in test_sts_access_denied
    self, response, 'AccessDenied', 'AWS Config does not have permission to assume the IAM role.')
  File "/Users/rafih/pro-service/virt-rdk/EEFS_NOT_ENCRYPTED/EEFS_NOT_ENCRYPTED_test.py", line 124, in assert_customer_error_response
    test_class.assertEqual(customer_error_code, response['customerErrorCode'])
AssertionError: 'AccessDenied' != 'InvalidParameterValueException'

Stdout:
{'internalErrorMessage': 'Parameter value is invalid', 'customerErrorCode': 'InvalidParameterValueException', 'internalErrorDetails': 'An ValueError was raised during the validation of the Parameter value', 'customerErrorMessage': 'Invalid Parameter, length is less than zero'}

======================================================================
FAIL: test_sts_unknown_error (EEFS_NOT_ENCRYPTED_test.TestStsErrors)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/rafih/pro-service/virt-rdk/EEFS_NOT_ENCRYPTED/EEFS_NOT_ENCRYPTED_test.py", line 155, in test_sts_unknown_error
    self, response, 'InternalError', 'InternalError')
  File "/Users/rafih/pro-service/virt-rdk/EEFS_NOT_ENCRYPTED/EEFS_NOT_ENCRYPTED_test.py", line 124, in assert_customer_error_response
    test_class.assertEqual(customer_error_code, response['customerErrorCode'])
AssertionError: 'InternalError' != 'InvalidParameterValueException'

Stdout:
{'internalErrorMessage': 'Parameter value is invalid', 'customerErrorCode': 'InvalidParameterValueException', 'internalErrorDetails': 'An ValueError was raised during the validation of the Parameter value', 'customerErrorMessage': 'Invalid Parameter, length is less than zero'}

----------------------------------------------------------------------

```
Replication steps:
1 . Create a default rule with some parameter
2 . modify "`evaluate_parameters`" function to raise some exception
3 . run local test, if evaluate_parameters raise any exception then common testing function fails.

I think this is because in lambda_handler function we are evaluating the parameter before creating the config client.

**Comment by jongogogo** [comment]
The only exception expected by the boiler plate from evaluate_parameters() is ValueError.  Need to add other type of Error in ~L290 of the template.
