### ISSUE TITLE
Windows - RDK Modify input-parameters doesn't work

### ISSUE THREAD

**Issue by jongogogo** [awslabs/aws-config-rdk#16]
C:\Users\jrault\AppData\Local\Programs\Python\Python36\Scripts>python rdk modify iam-mfa-enabled --input-parameters '{"WhitelistedUserList":"ARIAWERTYUFDSSS"}'
Running modify!
Error parsing input parameter JSON.  Make sure your JSON keys and values are enclosed in double quotes and your input-parameters string is enclosed in single quotes.
Traceback (most recent call last):
  File "rdk", line 32, in <module>
    return_val = my_rdk.process_command()
  File "C:\Users\jrault\AppData\Local\Programs\Python\Python36\lib\site-packages\rdk\rdk.py", line 56, in process_command
    exit_code = method_to_call()
  File "C:\Users\jrault\AppData\Local\Programs\Python\Python36\lib\site-packages\rdk\rdk.py", line 288, in modify
    self.__write_params_file()
  File "C:\Users\jrault\AppData\Local\Programs\Python\Python36\lib\site-packages\rdk\rdk.py", line 774, in __write_params_file
    raise e
  File "C:\Users\jrault\AppData\Local\Programs\Python\Python36\lib\site-packages\rdk\rdk.py", line 771, in __write_params_file
    my_input_params = json.loads(self.args.input_parameters, strict=False)
  File "C:\Users\jrault\AppData\Local\Programs\Python\Python36\lib\json\__init__.py", line 367, in loads
    return cls(**kw).decode(s)
  File "C:\Users\jrault\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\jrault\AppData\Local\Programs\Python\Python36\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by michaelborchert** [comment]
This was an issue with the way Window escapes quotes being different from Mac/Linux and not being called out in the documentation.  I've added Windows-specific examples on how to pass in input parameters in the readme.
