### ISSUE TITLE
Windows - Test-local doesn't work when the rule name has hyphen

### ISSUE THREAD

**Issue by jongogogo** [awslabs/aws-config-rdk#17]
rdk test-local cloudtrail-lfi-enabled
Running local test!
Testing cloudtrail-lfi-enabled
cloudtrail-lfi-enabled_test.py
Traceback (most recent call last):
  File "rdk", line 32, in <module>
    return_val = my_rdk.process_command()
  File "C:\Users\jrault\AppData\Local\Programs\Python\Python36\lib\site-packages\rdk\rdk.py", line 56, in process_command
    exit_code = method_to_call()
  File "C:\Users\jrault\AppData\Local\Programs\Python\Python36\lib\site-packages\rdk\rdk.py", line 463, in test_local
    results = unittest.TextTestRunner(buffer=True, verbosity=2).run(self.__create_test_suite(test_dir))
  File "C:\Users\jrault\AppData\Local\Programs\Python\Python36\lib\site-packages\rdk\rdk.py", line 608, in __create_test_suite
    suites = [unittest.defaultTestLoader.loadTestsFromName(test) for test in tests]
  File "C:\Users\jrault\AppData\Local\Programs\Python\Python36\lib\site-packages\rdk\rdk.py", line 608, in <listcomp>
    suites = [unittest.defaultTestLoader.loadTestsFromName(test) for test in tests]
  File "C:\Users\jrault\AppData\Local\Programs\Python\Python36\lib\unittest\loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "C:\Users\jrault\AppData\Local\Programs\Python\Python36\Scripts\cloudtrail-lfi-enabled\cloudtrail-lfi-enabled_test.py", line 22
    import cloudtrail-lfi-enabled as rule
                     ^
SyntaxError: invalid syntax

**Comment by bmorrissirromb** [comment]
As of Python 3.7, the `loader.py` file in question has been updated to use `module = __import__(module_name)`, which allows for the import of modules with hyphens in their name.

I would recommend using a newer version of Python to resolve this issue. RDK is specific in requiring Python 3.7+.
