### ISSUE TITLE
Git merge conflict committed in master

### ISSUE THREAD

**Issue by mwarkentin** [awslabs/aws-config-rdk#202]
https://github.com/awslabs/aws-config-rdk/blob/master/rdk/rdk.py#L686-L693

This is breaking `rdk init` when I attempted to run it myself:

```
$ rdk init -p wave-tmp-local
Traceback (most recent call last):
  File "/Users/mwarkentin/.local/bin/rdk", line 11, in <module>
    load_entry_point('rdk==0.6.1', 'console_scripts', 'rdk')()
  File "/Users/mwarkentin/.local/pipx/venvs/rdk/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/mwarkentin/.local/pipx/venvs/rdk/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/Users/mwarkentin/.local/pipx/venvs/rdk/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/Users/mwarkentin/.local/pipx/venvs/rdk/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/mwarkentin/.local/pipx/venvs/rdk/lib/python3.7/site-packages/rdk/cli.py", line 13, in <module>
    from rdk import rdk
  File "/Users/mwarkentin/.local/pipx/venvs/rdk/lib/python3.7/site-packages/rdk/rdk.py", line 686
    <<<<<<< HEAD
    ^
IndentationError: expected an indented block
```

**Comment by michaelborchert** [comment]
Should be fixed now.  Thanks!

**Comment by michaelborchert** [comment]
Should be fixed now.  Thanks for your patience over the weekend!

 -M
