### ISSUE TITLE
Bug: Terraform templates are not included in release version

### ISSUE THREAD

**Issue by djlewis78** [awslabs/aws-config-rdk#272]
Using the latest release version of `aws-config-rdk`, version `0.7.11` there is an error when attempting to export terraform resources:

```$ rdk export -v '0.12' -f 'terraform' --all
Running export
Found Custom Rule.
Zipping RDS_ALLOWED_DB_SUBNET_GROUP
Zipping complete.
terraform version: 0.12
Traceback (most recent call last):
  File "/home/daniel/environment/python3.8/bin/rdk", line 33, in <module>
    sys.exit(load_entry_point('rdk==0.7.11', 'console_scripts', 'rdk')())
  File "/home/daniel/environment/python3.8/lib/python3.8/site-packages/rdk/cli.py", line 21, in main
    return_val = my_rdk.process_command()
  File "/home/daniel/environment/python3.8/lib/python3.8/site-packages/rdk/rdk.py", line 343, in process_command
    exit_code = method_to_call()
  File "/home/daniel/environment/python3.8/lib/python3.8/site-packages/rdk/rdk.py", line 1466, in export
    shutil.copy(tf_file_body, tf_file_path)
  File "/usr/lib/python3.8/shutil.py", line 415, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.8/shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/home/daniel/environment/python3.8/lib/python3.8/site-packages/rdk/template/terraform/0.12/config_rule.tf
```

As mentioned in the last line, it seems that `setuptools` hasn't been provided the path to include the terraform template files.

I have reviewed the install using `python setup.py install` in the root directory of the project and found that there were missing entries in the `MANIFEST.in`.

**Comment by djlewis78** [comment]
PR link - https://github.com/awslabs/aws-config-rdk/pull/273
