### ISSUE TITLE
Support for Web Gateways

### ISSUE THREAD

**Issue by Gamecock** [awslabs/aws-config-rdk#321]
Corporate Web Gateways such as ZScalar doing SSL inspection replace the certificate with a new one.  Please enable a way to configure the cert to avoid SSL errors during init.

$ rdk init
Running init!
Traceback (most recent call last):
  File "c:\projects\aws\rdk\.venv\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "c:\projects\aws\rdk\.venv\lib\site-packages\urllib3\connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "c:\projects\aws\rdk\.venv\lib\site-packages\urllib3\connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "c:\projects\aws\rdk\.venv\lib\site-packages\urllib3\connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
  File "c:\projects\aws\rdk\.venv\lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "c:\projects\aws\rdk\.venv\lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\2259252\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\2259252\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Users\2259252\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\projects\aws\rdk\.venv\lib\site-packages\botocore\httpsession.py", line 344, in send
    urllib_response = conn.urlopen(
  File "c:\projects\aws\rdk\.venv\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "c:\projects\aws\rdk\.venv\lib\site-packages\urllib3\util\retry.py", line 507, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "c:\projects\aws\rdk\.venv\lib\site-packages\urllib3\packages\six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "c:\projects\aws\rdk\.venv\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "c:\projects\aws\rdk\.venv\lib\site-packages\urllib3\connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "c:\projects\aws\rdk\.venv\lib\site-packages\urllib3\connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "c:\projects\aws\rdk\.venv\lib\site-packages\urllib3\connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
  File "c:\projects\aws\rdk\.venv\lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "c:\projects\aws\rdk\.venv\lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\2259252\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\2259252\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Users\2259252\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Projects\AWS\RDK\.venv\Scripts\rdk-script.py", line 11, in <module>
    load_entry_point('rdk==0.8.2', 'console_scripts', 'rdk')()
  File "c:\projects\aws\rdk\.venv\lib\site-packages\rdk\cli.py", line 22, in main
    return_val = my_rdk.process_command()
  File "c:\projects\aws\rdk\.venv\lib\site-packages\rdk\rdk.py", line 449, in process_command
    exit_code = method_to_call()
  File "c:\projects\aws\rdk\.venv\lib\site-packages\rdk\rdk.py", line 467, in init
    identity_details = self.__get_caller_identity_details(my_session)
  File "c:\projects\aws\rdk\.venv\lib\site-packages\rdk\rdk.py", line 2654, in __get_caller_identity_details
    response = my_sts.get_caller_identity()
  File "c:\projects\aws\rdk\.venv\lib\site-packages\botocore\client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "c:\projects\aws\rdk\.venv\lib\site-packages\botocore\client.py", line 691, in _make_api_call
    http, parsed_response = self._make_request(
  File "c:\projects\aws\rdk\.venv\lib\site-packages\botocore\client.py", line 711, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "c:\projects\aws\rdk\.venv\lib\site-packages\botocore\endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "c:\projects\aws\rdk\.venv\lib\site-packages\botocore\endpoint.py", line 136, in _send_request
    while self._needs_retry(attempts, operation_model, request_dict,
  File "c:\projects\aws\rdk\.venv\lib\site-packages\botocore\endpoint.py", line 253, in _needs_retry
    responses = self._event_emitter.emit(
  File "c:\projects\aws\rdk\.venv\lib\site-packages\botocore\hooks.py", line 357, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "c:\projects\aws\rdk\.venv\lib\site-packages\botocore\hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "c:\projects\aws\rdk\.venv\lib\site-packages\botocore\hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "c:\projects\aws\rdk\.venv\lib\site-packages\botocore\retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "c:\projects\aws\rdk\.venv\lib\site-packages\botocore\retryhandler.py", line 250, in __call__
    should_retry = self._should_retry(attempt_number, response,
  File "c:\projects\aws\rdk\.venv\lib\site-packages\botocore\retryhandler.py", line 277, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "c:\projects\aws\rdk\.venv\lib\site-packages\botocore\retryhandler.py", line 316, in __call__
    checker_response = checker(attempt_number, response,
  File "c:\projects\aws\rdk\.venv\lib\site-packages\botocore\retryhandler.py", line 222, in __call__
    return self._check_caught_exception(
  File "c:\projects\aws\rdk\.venv\lib\site-packages\botocore\retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
  File "c:\projects\aws\rdk\.venv\lib\site-packages\botocore\endpoint.py", line 200, in _do_get_response
    http_response = self._send(request)
  File "c:\projects\aws\rdk\.venv\lib\site-packages\botocore\endpoint.py", line 269, in _send
    return self.http_session.send(request)
  File "c:\projects\aws\rdk\.venv\lib\site-packages\botocore\httpsession.py", line 371, in send
    raise SSLError(endpoint_url=request.url, error=e)
botocore.exceptions.SSLError: SSL validation failed for https://sts.amazonaws.com/ [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)

**Comment by bmorrissirromb** [comment]
I think this is unfortunately beyond the scope of what RDK can reasonably handle. This would require every AWS API call made by RDK to ignore SSL validation, if specified. That would add a lot of maintenance overhead to the solution without a lot of benefit. I'd recommend working with your web gateway administrator to see if there are any alternatives, as this problem seems like it would affect many more tools than just RDK (ie. any tool that makes an AWS API call).

**Comment by Gamecock** [comment]
I'm not asking for you to ignore SSL errors, I'm asking for a way for me to provide the trusted cert.
