### ISSUE TITLE
Module 'boto3.session' has no attribute 'region_name' - RDK export error

### ISSUE THREAD

**Issue by Alex78460** [awslabs/aws-config-rdk#326]
Hello,

It looks like we have an issue with latest RDK v.0.8.3 & export feature.

% rdk -v                                                       
rdk 0.8.3
% rdk -r eu-west-1 export MY_FIRST_RULE -f terraform -v 0.12   
Running export
Found Custom Rule.
Zipping MY_FIRST_RULE
Traceback (most recent call last):
  File "/usr/local/bin/rdk", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/rdk/cli.py", line 53, in main
    return_val = my_rdk.process_command()
  File "/usr/local/lib/python3.9/site-packages/rdk/rdk.py", line 490, in process_command
    exit_code = method_to_call()
  File "/usr/local/lib/python3.9/site-packages/rdk/rdk.py", line 1985, in export
    s3_dst = self.__package_function_code(rule_name, rule_params)
  File "/usr/local/lib/python3.9/site-packages/rdk/rdk.py", line 3007, in __package_function_code
    tmp_src = shutil.make_archive(os.path.join(tempfile.gettempdir(), rule_name+session.region_name), 'zip', s3_src_dir)
AttributeError: module 'boto3.session' has no attribute 'region_name'

**Comment by jarrettandrulis** [comment]
Put in a Pull Request to fix this, @rickychau2780 please review the changes
