### ISSUE TITLE
`deploy` command doesn't display usage instructions when run with no args

### ISSUE THREAD

**Issue by michaelborchert** [awslabs/aws-config-rdk#61]
Need to improve arg parsing to display usage instructions if command is called without rule name(s), --rulesets flag, or --all flag.

Current error:

(rdk-test) [mborch] rdk-test $ rdk deploy
Running deploy!
Traceback (most recent call last):
  File "/Users/mborch/Code/rdk-test/bin/rdk", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/Users/mborch/Code/aws-config-rdk/bin/rdk", line 32, in <module>
    return_val = my_rdk.process_command()
  File "/Users/mborch/Code/aws-config-rdk/rdk/rdk.py", line 58, in process_command
    exit_code = method_to_call()
  File "/Users/mborch/Code/aws-config-rdk/rdk/rdk.py", line 448, in deploy
    rule_names = self.__get_rule_list_for_command()
  File "/Users/mborch/Code/aws-config-rdk/rdk/rdk.py", line 1116, in __get_rule_list_for_command
    cleaned_rule_name = self.__clean_rule_name(self.args.rulename[0])
IndexError: list index out of range

**Comment by michaelborchert** [comment]
Thanks for the fix!
