### ISSUE TITLE
exception when using undeploy in python2.7

### ISSUE THREAD

**Issue by rafihm** [awslabs/aws-config-rdk#85]
`rdk undeploy` throws below exception when using python2.7

$ rdk undeploy undeploy-test
Delete specified Rules and Lamdba Functions from your AWS Account? (y/N): y
Traceback (most recent call last):
  File "/usr/local/bin/rdk", line 32, in <module>
    return_val = my_rdk.process_command()
  File "/Library/Python/2.7/site-packages/rdk/rdk.py", line 67, in process_command
    exit_code = method_to_call()
  File "/Library/Python/2.7/site-packages/rdk/rdk.py", line 468, in undeploy
    my_input = input("Delete specified Rules and Lamdba Functions from your AWS Account? (y/N): ")
  File "<string>", line 1, in <module>
NameError: name 'y' is not defined

**Comment by rafihm** [comment]
I think we need to use `raw_input` instead of `input`

**Comment by michaelborchert** [comment]
Closed by PR #87!  Thanks for finding this!
